[package]
name = "concreter"
version = "0.0.1"
authors = ["Louis <836250617@qq.com>"]
edition = "2021"

[dependencies]
agdb = {vserion = "0.5.1", features = []}
dotenv = "0.15.0"
snafu = {version = "0.7.5", features = ["std", "rust_1_61"]}
