apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: concreter
    name: postgres
    role: db
spec:
  selector:
    name: postgres
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30009
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
    app: concreter
    role: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
      app: concreter
      role: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: postgres
        app: concreter
        role: db
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          hostPath:
            path: /Users/louis/web/Concreter/pg_db
