apiVersion: v1
kind: Service
metadata:
  name: rpc-py
  labels:
    app: concreter
    name: rpc-py
    role: rpc
spec:
  selector:
    name: rpc-py
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-py
  labels:
    name: rpc-py
    app: concreter
    role: rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rpc-py
      app: concreter
      role: rpc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: rpc-py
        app: concreter
        role: rpc
    spec:
      containers:
        - name: rpc-py
          image: rpc-py
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: OPENAI_API_KEY
          ports:
            - containerPort: 50051
