# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nlp_pb2 as nlp__pb2


class NlpStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ner = channel.unary_unary(
                '/nlp.Nlp/Ner',
                request_serializer=nlp__pb2.NerRequest.SerializeToString,
                response_deserializer=nlp__pb2.NerReply.FromString,
                )


class NlpServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NlpServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ner': grpc.unary_unary_rpc_method_handler(
                    servicer.Ner,
                    request_deserializer=nlp__pb2.NerRequest.FromString,
                    response_serializer=nlp__pb2.NerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlp.Nlp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Nlp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlp.Nlp/Ner',
            nlp__pb2.NerRequest.SerializeToString,
            nlp__pb2.NerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
