# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sym.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsym.proto\x12\x03sym\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x10\x43onvertMdRequest\x12\n\n\x02md\x18\x01 \x01(\t\"\x1d\n\x0e\x43onvertMdReply\x12\x0b\n\x03sym\x18\x01 \x01(\t*!\n\tValueType\x12\n\n\x06NUMBER\x10\x00\x12\x08\n\x04\x45XPR\x10\x01\x32u\n\x03Sym\x12.\n\x08SayHello\x12\x11.sym.HelloRequest\x1a\x0f.sym.HelloReply\x12>\n\x10\x43onvertMdFormula\x12\x15.sym.ConvertMdRequest\x1a\x13.sym.ConvertMdReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sym_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VALUETYPE']._serialized_start=142
  _globals['_VALUETYPE']._serialized_end=175
  _globals['_HELLOREQUEST']._serialized_start=18
  _globals['_HELLOREQUEST']._serialized_end=46
  _globals['_HELLOREPLY']._serialized_start=48
  _globals['_HELLOREPLY']._serialized_end=77
  _globals['_CONVERTMDREQUEST']._serialized_start=79
  _globals['_CONVERTMDREQUEST']._serialized_end=109
  _globals['_CONVERTMDREPLY']._serialized_start=111
  _globals['_CONVERTMDREPLY']._serialized_end=140
  _globals['_SYM']._serialized_start=177
  _globals['_SYM']._serialized_end=294
# @@protoc_insertion_point(module_scope)
